flowchart TD
    A[Login] -->|Log into app| B(User Loading page)
    B --> C{What kind of user?}
    
    C -->|Operations Manager| D[Ops Manager Views]
    D -->DA[Sensor Monitoring View]
    DA -->DAA[Sensor Uptime]
    DA -->DAB[Charts wirh Alerts]
    D -->DB[Maintenance View]
    DB -->DBA[Alert Setup Screen]
    DB -->DBB[Calendar Screen for Scheduling Maintenance]
    D -->DC[Charts View]
    DC -->DCA[Historical Chart Data]
    D -->DD[Reporting View]
    DD -->DDA[Report sensors that are broken]
    DD -->DDB[Error Logging]


    C -->|Administrator| E[Administrator Views] 
    E --> EA[Account Management]
    EA -->EAA[Setup and Remove Accounts]
    EA -->EAB[Manage user permissions]
    E --> EB[Administrator Alert System]
    EB -->EBA[Alert for Login Attempts]
    EB -->EBB[Reviews of User Access]
    E -->EC[Sensor Management View]
    EC -->ECA[Manage Sensors]
    EC -->ECB[Sensor Upgrading]
    EC -->ECC[Sensor Configuration]
    E -->ED[Data Storage and Backup View]
    ED -->EDA[Database Storage View]
    EDA -->EDAA[Manage Usage]
    EDA -->EDAB[Create Backups]

    C -->|Environmental Scientist| F[Environmental Scientist Views]
    F -->FA[Sensor account management View]
    FA -->FAA[Sensor Settings]
    FA -->FAB[Sensor History Logs]
    F --> FB[Historical View]
    FB -->FBA[Sensor Charts]
    FB -->FBB[Graphs with sensor data]
    FB -->FBC[Filtering settings for data]
    F -->FC[Map View]
    FC -->FCA[Interactive Map]
    FC -->FCB[Alert System on Map]
    FC -->FCC[Navigation to Sensors]
    FC -->FCD[Check Sensor Uptime]
    F -->FD[Report Generation View]
    FD -->FDA[Query Historical Data]
    FD -->FDB[Distinquish Anomalies]
